#!/bin/bash
ARGS="$@"
MAIN="org.clueminer.cli.Main"
jarfile="$(ls -t target/*jar-with-dependencies.jar | head -1)"
if [[ -f "$jarfile" ]]; then
  java -jar $jarfile $ARGS
else
  path="target/lib"
  if [[ -d $path ]]; then
    CLASSPATH=$(find "." -name '*.jar' | xargs echo | tr ' ' ':')
    java -cp $CLASSPATH $MAIN $ARGS
  else
    mvn "-Dexec.args=-classpath %classpath $MAIN $ARGS" -Dexec.executable=java -Dexec.classpathScope=runtime org.codehaus.mojo:exec-maven-plugin:1.2.1:exec
  fi
fi
